# IPTC PMD Std 2014 / ExifTool Tags / PMD Investigation Guide - YAML format
# Test Guide below refers to the JSON structure exported by ExifTool
# HELP: only three types of keys:
# 1/ the ExifTool field name (the ":" is replaced by a "_" for YAML reasons!!)
# 2/ the "label": a sequence of IPTC Photo Metadata and technical standard labels, separated by |
# 2/ the "output": a sequence of target object for the output, separated by commas
# Field structures have to follow the YAML syntax: they have to be indented by at least 2 spaces
# Fields inside structures have as value the same as the "label" of top level fields.
# BE AWARE: this Guide lists only the field names in structures but not how they are held,
# as single, plain value or in an array. This is derived from the ExifTool JSON retrieved from the image.
# Status: 2016-11-20, mws
IFD0_Artist :
  label: Creator (Exif)| Exif/TIFF Artist
  output: exif,rights
IFD0_Copyright:
  label: Copyright Notice (Exif)|Exif/TIFF Copyright
  output: exif,rights
ExifIFD_DateTimeOriginal:
  label: Date Created (Exif)|Exif/IFD DateTimeOriginal
  output: exif,admin
IFD0_ImageDescription:
  label: Description (Exif)|Exif/TIFF ImageDescription
  output: exif,admin
ExifTool_ExifToolVersion: 
  label: Exiftool Version|NA (Exiftool Version)
  output: any
System_FileName:
  label: File Name|NA (File Name)
  output: none
IPTC_By-line: 
  label: "Creator (IIM)|IIM 2:80 By-line"
  output: iim,rights
IPTC_By-lineTitle: 
  label: "Creator Jobtitle (IIM)|IIM 2:85 By-line Title"
  output: iim,rights
IPTC_Caption-Abstract:
   label: "Description (IIM)|IIM 2:120 Caption/Abstract"
   output: iim,gimgcont
IPTC_City: 
  label: "City (legacy) (IIM)|IIM 2:90 City"
  output: iim,location
IPTC_CopyrightNotice: 
  label: "Copyright Notice (IIM)|IIM 2:116 Copyright Notice"
  output: iim,rights
IPTC_Country-PrimaryLocationName:
  label: "Country (legacy) (IIM)|IIM 2:101 Country/Primary Location Name"
  output: iim,locaction
IPTC_Country-PrimaryLocationCode:
  label: "Country Code (legacy) (IIM)|IIM 2:101 Country/Primary Location Name"
  output: iim,location
IPTC_Credit:
  label: "Credit (IIM)|IIM 2:110 Credit"
  output: iim,rights
IPTC_DateCreated: 
  label: "Date Created/Date (IIM)|IIM 2:55 Date Created"
  output: iim,admin
IPTC_Headline: 
  label: "Headline (IIM)|IIM 2:105 Headline"
  output: iim,gimgcont
IPTC_Keywords: 
  label: "Keywords (IIM)|IIM 2:25 Keywords"
  output: iim,gimgcont
IPTC_ObjectAttributeReference: 
  label: "Intellectual Genre (IIM)|IIM 2:04 Object Attribute Reference"
  output: iim,gimgcont
IPTC_ObjectName: 
  label: "Title (IIM)|IIM 2:05 Object Name"
  output: iim,admin
IPTC_OriginalTransmissionReference: 
  label: "Job Id (IIM)|IIM 2:103 Original Transmission Reference"
  output: iim,admin
IPTC_Province-State: 
  label: "Province/State (IIM)|IIM 2:95 Province/State"
  output: iim,location
IPTC_Source: 
  label: "Source (IIM)|IIM 2:115 Source"
  output: iim,rights
IPTC_SpecialInstructions: 
  label: "Instructions (IIM)|IIM 2:40 Special Instruction"
  output: iim,admin
IPTC_Sub-location: 
  label: "Sublocation (legacy) (IIM)|IIM 2:92 Sublocation"
  output: iim,location
IPTC_SubjectReference: 
  label: "Subject Code (IIM)|IIM 2:12 Subject Reference"
  output: iim,gimgcont
IPTC_TimeCreated: 
  label: "Date Created/Time (IIM)|IIM 2:20 Time Created"
  output: iim,admin
IPTC_Writer-Editor: 
  label: "Description Writer (IIM)|IIM 2:122 Writer/Editor"
  output: iim,admin
XMP-iptcExt_AboutCvTerm:
  label: "CV Term About Image (XMP) |XMP iptc4xmpExt:ArtworkOrObject"
  output: xmp,gimgcont
  CvId: "CV Id (XMP) |XMP Iptc4xmpExt:CvId"
  CvTermId: " CV Term Id (XMP) |XMP Iptc4xmpExt:CvTermId"
  CvTermName: "CV Term Name (XMP) |XMP Iptc4xmpExt:CvTermName"
  CvTermRefinedAbout: "Refined About (XMP) |XMP Iptc4xmpExt:CvTermRefinedAbout"
XMP-iptcExt_AdditionalModelInformation:
  label: "Additional Model Info (XMP) |XMP iptc4xmpExt:AddlModelInfo"
  output: xmp,person
XMP-iptcExt_ArtworkOrObject:
  label: "Artwork or Object in the Image (XMP) |XMP Iptc4xmpExt:ArtworkOrObject"
  output: xmp,othings
  AOCircaDateCreated: "Circa Date Created (XMP) |XMP Iptc4xmpExt:AOCircaDateCreated"
  AOContentDescription: "Content Description (XMP) |XMP Iptc4xmpExt:AOContentDescription"
  AOContributionDescription: "Contribution Description (XMP) |XMP Iptc4xmpExt:AOContributionDescription"
  AOCopyrightNotice: "Copyright Notice (XMP) |XMP Iptc4xmpExt:AOCopyrightNotice"
  AOCreator: "Creator (XMP) |XMP Iptc4xmpExt:AOCreator"
  AOCreatorId: "Creator Id (XMP) |XMP Iptc4xmpExt:AOCreatorId"
  AOCurrentCopyrightOwnerId: "Copyright Owner Id (XMP) |XMP Iptc4xmpExt:AOCurrentCopyrightOwnerId"
  AOCurrentCopyrightOwnerName: "Copyright Owner Name (XMP) |XMP Iptc4xmpExt:AOCurrentCopyrightOwnerName"
  AOCurrentLicensorId: "Licensor Id (XMP) |XMP Iptc4xmpExt:AOCurrentLicensorId"
  AOCurrentLicensorName: "Licensor Name (XMP) |XMP Iptc4xmpExt:AOCurrentLicensorName"
  AODateCreated: "Date Created (XMP) |XMP Iptc4xmpExt:AODateCreated"
  AOPhysicalDescription: "Physical Description (XMP) |XMP Iptc4xmpExt:AOPhysicalDescription"
  AOSource: "Source (XMP) |XMP Iptc4xmpExt:AOSource"
  AOSourceInvNo: "Source Inventory No (XMP) |XMP Iptc4xmpExt:AOSourceInvNo"
  AOSourceInvURL: "Source Inventory URL (XMP) |XMP Iptc4xmpExt:AOSourceInvURL"
  AOStylePeriod: "Style Period (XMP) |XMP Iptc4xmpExt: " 
  AOTitle: "Title (XMP) |XMP Iptc4xmpExt:AOStylePeriod"
XMP-photoshop_AuthorsPosition:
  label: "Creator Jobtitle (XMP) |XMP photoshop:AuthorsPosition"
  output: xmp,rights
XMP-photoshop_CaptionWriter:
  label: "Description Writer (XMP) |XMP photoshop:CaptionWriter"
  output: xmp,admin
XMP-photoshop_City:
  label: "City (legacy) (XMP) |XMP photoshop:City"
  output: xmp,location
XMP-plus_CopyrightOwner:
  label: "Copyright Owner (XMP) |XMP plus:CopyrightOwner"
  output: xmp,rights
  CopyrightOwnerID: "Id (XMP) |XMP plus:CopyrightOwnerID"
  CopyrightOwnerName: "Name (XMP) |XMP plus:CopyrightOwnerName"
XMP-photoshop_Country:
  label: "County (legacy) (XMP) |XMP photoshop:Country"
  output: xmp,location
XMP-iptcCore_CountryCode:
  label: "Country Code (legacy) (XMP) |XMP Iptc4xmpCore:CountryCode"
  output: xmp,location
XMP-dc_Creator:
  label: "Creator (XMP) |XMP dc:Creator"
  output: xmp,rights
XMP-iptcCore_CreatorContactInfo:
  label: "Creator's Contact Info (XMP) |XMP Iptc4xmpCore:CreatorContactInfo"
  output: xmp,rights
  CiAdrCity: "City (XMP) |XMP Iptc4xmpCore:CiAdrCity"
  CiAdrCtry: "Country (XMP) |XMP Iptc4xmpCore:CiAdrCtry"
  CiAdrExtadr: "Extended Address (XMP) |XMP Iptc4xmpCore:CiAdrExtadr"
  CiAdrPcode: "Postal Code (XMP) |XMP Iptc4xmpCore:CiAdrPcode"
  CiAdrRegion: "Region (XMP) |XMP Iptc4xmpCore:CiAdrRegion"
  CiEmailWork: "Email-Work (XMP) |XMP Iptc4xmpCore:CiEmailWork"
  CiTelWork: "Phone-Work (XMP) |XMP Iptc4xmpCore:CiTelWork"
  CiUrlWork: "Web Address-Work (XMP) |XMP Iptc4xmpCore:CiUrlWork"
XMP-photoshop_Credit:
  label: "Credit Line (XMP) |XMP photoshop:Credit"
  output: xmp,rights
XMP-photoshop_DateCreated:
  label: "Date Created (XMP) |XMP photoshop:DateCreated"
  output: xmp,admin
XMP-dc_Description:
  label: "Description (XMP) |XMP dc:Description"
  output: xmp,gimgcont
XMP-iptcExt_DigitalImageGUID:
  label: "Digital Image GUID (XMP) |XMP Iptc4xmpExt:DigitalImageGUID"
  output: xmp,admin
XMP-iptcExt_DigitalSourceType:
  label: "Digital Source Type (XMP) |XMP Iptc4xmpExt:DigitalSourceType"
  output: xmp,admin
XMP-iptcExt_EmbdEncRightsExpr:
  label: "Embedded Encoded Rights Expression (XMP) |XMP Iptc4xmpExt:EmbdEncRightsExpr"
  output: xmp,rights
  EncRightsExpr: "Encoded Rights Expression (XMP) |XMP Iptc4xmpExt:EncRightsExpr"
  RightsExprEncType: "Rights Expr Encoding Type (XMP) |XMP Iptc4xmpExt:RightsExprEncType"
  RightsExprLangId: "Rights Expr Language Id (XMP) |XMP Iptc4xmpExt:RightsExprLangId"
XMP-iptcExt_Event:
  label: "Event (XMP) |XMP Iptc4xmpExt:Event"
  output: xmp,othings
XMP-iptcExt_Genre:
  label: "Genre (of the image) (XMP) |XMP iptc4xmpExt:Genre"
  output: xmp,gimgcont
  CvId: "CV Id (XMP) |XMP Iptc4xmpExt:CvId"
  CvTermId: " CV Term Id (XMP) |XMP Iptc4xmpExt:CvTermId"
  CvTermName: "CV Term Name (XMP) |XMP Iptc4xmpExt:CvTermName"
  CvTermRefinedAbout: "Refined About (XMP) |XMP Iptc4xmpExt:CvTermRefinedAbout"
XMP-photoshop_Headline:
  label: "Headline (XMP) |XMP Iptc4xmpExt:Headline"
  output: xmp,gimgcont
XMP-plus_ImageCreator:
  label: "Image Creator (XMP) |XMP plus:ImageCreator"
  output: xmp,rights
  ImageCreatorID: "Id (XMP) |XMP plus:ImageCreatorID"
  ImageCreatorName: "Name (XMP) |XMP plus:ImageCreatorName"
XMP-plus_ImageCreatorImageID:
  label: "Image Creator's Image Id (XMP) |XMP plus:ImageCreatorImageID"
  output: xmp,rights
XMP-plus_ImageSupplier:
  label: "Image Supplier (XMP) |XMP plus:ImageSupplier"
  output: xmp,lic
  ImageSupplierID: "Id (XMP) |XMP plus:ImageSupplierID"
  ImageSupplierName: "Name (XMP) |XMP plus:ImageSupplierName"
XMP-plus_ImageSupplierImageID:
  label: "Image Supplier's Image Id (XMP) |XMP plus:ImageSupplierImageID"
  output: xmp,lic
XMP-photoshop_Instructions:
  label: "Instructions (XMP) |XMP photoshop:Instructions" 
  output: xmp,admin
XMP-iptcCore_IntellectualGenre:
  label: "Intellectual Genre (XMP) |XMP Iptc4xmpCore:IntellectualGenre" 
  output: xmp,gimgcont
XMP-plus_Licensor:
  label: "Licensor (XMP) |XMP plus:Licensor" 
  output: xmp,lic
  LicensorCity: "City (XMP) |XMP plus:LicensorCity"
  LicensorCountry: "Country (XMP) |XMP plus:LicensorCountry"
  LicensorEmail: "Email (XMP) |XMP plus: " 
  LicensorExtendedAddress: "Ext Address (XMP) |XMP plus:LicensorEmail"
  LicensorID: "Id (XMP) |XMP plus:LicensorID"
  LicensorName: "Name (XMP) |XMP plus:LicensorName"
  LicensorPostalCode: "Postal Code (XMP) |XMP plus:LicensorPostalCode"
  LicensorRegion: "Region (XMP) |XMP plus:LicensorRegion"
  LicensorStreetAddress: "Street (XMP) |XMP plus:LicensorStreetAddress"
  LicensorTelephone1: "Telephone 1 (XMP) |XMP plus:LicensorTelephone1"
  LicensorTelephone2: "Telephone 2 (XMP) |XMP plus:LicensorTelephone2"
  LicensorURL: "Web URL (XMP) |XMP plus:LicensorURL"
XMP-iptcExt_LinkedEncRightsExpr:
  label: "Linked Encoded Rights Expression (XMP) |XMP Iptc4xmpExt:LinkedEncRightsExpr" 
  output: xmp,rights
  LinkedRightsExpr: "Linked Rights Expression (XMP) |XMP Iptc4xmpExt:LinkedRightsExpr" 
  RightsExprEncType: "Rights Expr Encoding Type (XMP) |XMP Iptc4xmpExt:RightsExprEncType" 
  RightsExprLangId: "Rights Expr Language Id (XMP) |XMP Iptc4xmpExt:RightsExprLangId" 
XMP-iptcCore_Location:
  label: "Location (legacy) (XMP) |XMP Iptc4xmpCore:Location" 
  output: xmp,location
XMP-iptcExt_LocationCreated:
  label: "Location Created (XMP) |XMP Iptc4xmpExt:LocationCreated" 
  output: xmp,location
  City: "City (XMP) |XMP Iptc4xmpExt:City"
  CountryCode: "Country Code (XMP) |XMP Iptc4xmpExt:CountryCode"
  CountryName: "Country Name (XMP) |XMP Iptc4xmpExt:CountryName"
  LocationId: "Location Id (XMP)|XMP Iptc4xmpExt:LocationId"
  ProvinceState: "Province/State (XMP) |XMP Iptc4xmpExt:ProvinceState"
  Sublocation: "Sublocation (XMP) |XMP Iptc4xmpExt:Sublocation"
  WorldRegion: "WorldRegion (XMP) |XMP Iptc4xmpExt:WorldRegion"
XMP-iptcExt_LocationShown:
  label: "Location Shown (XMP) |XMP Iptc4xmpExt:LocationShown"
  output: xmp,location
  City: "City (XMP) |XMP Iptc4xmpExt:City"
  CountryCode: "Country Code (XMP) |XMP Iptc4xmpExt:CountryCode"
  CountryName: "Country Name (XMP) |XMP Iptc4xmpExt:CountryName"
  LocationId: "Location Id (XMP)|XMP Iptc4xmpExt:LocationId"
  ProvinceState: "Province/State (XMP) |XMP Iptc4xmpExt:ProvinceState"
  Sublocation: "Sublocation (XMP) |XMP Iptc4xmpExt:Sublocation"
  WorldRegion: "WorldRegion (XMP) |XMP Iptc4xmpExt:WorldRegion"
XMP-iptcExt_MaxAvailHeight:
  label: "Max Available Height (XMP) |XMP Iptc4xmpExt:MaxAvailHeight"
  output: xmp,admin
XMP-iptcExt_MaxAvailWidth:
  label: "Max Available Width (XMP) |XMP Iptc4xmpExt:MaxAvailWidth"
  output: xmp,admin
XMP-plus_MinorModelAgeDisclosure:
  label: "Minor Model Age Disclosure (XMP) |XMP plus:MinorModelAgeDisclosure"
  output: xmp,admin
XMP-plus_ModelAge:
  label: "Model Age (XMP) |XMP plus:ModelAge"
  output: xmp,person
XMP-plus_ModelReleaseID:
  label: "Model Release Id (XMP) |XMP plus:ModelReleaseID"
  output: xmp,person
XMP-plus_ModelReleaseStatus:
  label: "Model Release Status (XMP) |XMP plus:ModelReleaseStatus"
  output: xmp,person
XMP-iptcExt_OrganisationInImageCode:
  label: "Organisation in Image - Code (XMP) |XMP Iptc4xmpExt:OrganisationInImageCode"
  output: xmp,othings
XMP-iptcExt_OrganisationInImageName:
  label: "Organisation in Image - Name (XMP) |XMP Iptc4xmpExt:OrganisationInImageName"
  output: xmp,othings
XMP-iptcExt_PersonInImage:
  label: "Person in Image (XMP) |XMP Iptc4xmpExt:PersonInImage"
  output: xmp,person
XMP-iptcExt_PersonInImageWDetails:
  label: "Person in Image with Details (XMP) |XMP Iptc4xmpExt:PersonInImageWDetails"
  output: xmp,person
  PersonCharacteristic:
    CvId: "CV Id (XMP) |XMP Iptc4xmpExt:CvId"
    CvTermId: " CV Term Id (XMP) |XMP Iptc4xmpExt:CvTermId"
    CvTermName: "CV Term Name (XMP) |XMP Iptc4xmpExt:CvTermName"
    CvTermRefinedAbout: "Refined About (XMP) |XMP Iptc4xmpExt:CvTermRefinedAbout"
  PersonDescription: "Description (XMP) |XMP Iptc4xmpExt:PersonDescription"
  PersonId: "Id (XMP) |XMP Iptc4xmpExt:PersonId"
  PersonName: "Name (XMP) |XMP Iptc4xmpExt:PersonName"
XMP-iptcExt_ProductInImage:
  label: "Product in Image (XMP) |XMP Iptc4xmpExt:ProductInImage"
  output: xmp,othings
  ProductDescription: "Description (XMP) |XMP Iptc4xmpExt:ProductDescription"
  ProductGTIN: "GTIN (XMP) |XMP Iptc4xmpExt:ProductGTIN"
  ProductName: "Name (XMP) |XMP Iptc4xmpExt:ProductName"
XMP-plus_PropertyReleaseID:
  label: "Property Release Id (XMP) |XMP plus:PropertyReleaseID"
  output: xmp,rights
XMP-plus_PropertyReleaseStatus:
  label: "Property Release Status (XMP) |XMP plus:PropertyReleaseStatus"
  output: xmp,rights
XMP-xmp_Rating:
  label: "Image Rating (XMP) |XMP xmp:Rating"
  output: xmp,gimgcont
XMP-iptcExt_RegistryID:
  label: "Registry Entry (XMP) |XMP Iptc4xmpExt:RegistryID"
  output: xmp,admin
  RegItemId: "Item Id (XMP) |XMP Iptc4xmpExt:RegItemId"
  RegOrgId: "Organisation Id (XMP) |XMP Iptc4xmpExt:RegOrgId"
  RegEntryRole: "Role (XMP)|XMP Iptc4xmpExt:RegEntryRole"
XMP-dc_Rights:
  label: "Copyright Notice (XMP) |XMP dc:Rights"
  output: xmp,rights
XMP-iptcCore_Scene:
  label: "Scene Code (XMP) |XMP Iptc4xmpExt:Scene"
  output: xmp,gimgcont
XMP-photoshop_Source:
  label: "Source (XMP) |XMP photoshop:Source"
  output: xmp,rights
XMP-photoshop_State:
  label: "State (legacy) (XMP) |XMP photoshop:State"
  output: xmp,location
XMP-dc_Subject:
  label: "Keywords (XMP) |XMP dc:Subject"
  output: xmp,gimgcont
XMP-iptcCore_SubjectCode:
  label: "Subject Code (XMP) |XMP Iptc4xmpCore:SubjectCode"
  output: xmp,gimgcont
XMP-dc_Title:
  label: "Title (XMP) |XMP dc:Title"
  output: xmp,admin
XMP-photoshop_TransmissionReference:
  label: "Job Id (XMP) |XMP photoshop:TransmissionReference"
  output: xmp,admin
XMP-xmpRights_UsageTerms:
  label: "Rights Usage Terms (XMP) |XMP xmpRights:UsageTerms"
  output: xmp,lic
XMP-xmpRights_WebStatement:
  label: "Web Statement of Rights (XMP) |XMP xmpRights:WebStatement"
  output: xmp,rights
XMP_XMPToolkit: 
  label: XMP Toolkit (XMP) |XMP 
  output: any
