# IPTC PMD Std 2014 / ExifTool Tags / PMD Matching Guide - YAML format
# Test Guide below refers to the JSON structure exported by ExifTool
# The Guide defines sets of metadata properties of different technical
#    format to be matched.
# Stautus: 2016-11-21, mws
match01:
  label: "Creator"
  props:
    - IPTC_By-line
    - XMP-dc_Creator
    - IFD0_Artist
match02:
  label: "Creator's Jobtitle"
  props:
    - IPTC_By-lineTitle
    - XMP-photoshop_AuthorsPosition
match03:
  label: "Description"
  props:
    - IPTC_Caption-Abstract
    - XMP-dc_Description
    - IFD0_ImageDescription
match04:
  label: "Copyright Notice"
  props:
    - IPTC_CopyrightNotice
    - XMP-dc_Rights
    - IFD0_Copyright
match05:
  label: "Credit"
  props:
    - IPTC_Credit
    - XMP-photoshop_Credit
match06:
  label: "Date Created (formats are different in IIM, XMP and Exif)"
  props:
    - IPTC_DateCreated
    - XMP-photoshop_DateCreated
    - ExifIFD_DateTimeOriginal
match14:
  label: "Time part of Date Created (IIM only) "
  props:
    - IPTC_TimeCreated
match07:
  label: "Headline"
  props:
    - IPTC_Headline
    - XMP-photoshop_Headline
match08:
  label: "Keywords"
  props:
    - IPTC_Keywords
    - XMP-dc_Subject
match09:
  label: "Title"
  props:
    - IPTC_ObjectName
    - XMP-dc_Title
match10:
  label: "Job Id"
  props:
    - IPTC_OriginalTransmissionReference
    - XMP-photoshop_TransmissionReference
match11:
  label: "Source"
  props:
    - IPTC_Source
    - XMP-photoshop_Source
match12:
  label: "Instructions"
  props:
    - IPTC_SpecialInstructions
    - XMP-photoshop_Instructions
match13:
  label: "Description Writer"
  props:
    - IPTC_Writer-Editor
    - XMP-photoshop_CaptionWriter

